language: php

services:
  - redis-server

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.0
    - php: 7.1
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.2
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.2.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY_VERSION="4.2.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - php -i | grep -i --color=never "Redis Version"
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv rehash; fi;
  - composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update

before_script: mkdir Snc && ln -s ../ Snc/RedisBundle
