language: php

services:
  - redis-server

matrix:
  include:
    - php: 7.0
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.2.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.3.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"
    - php: nightly
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="4.3.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv rehash; fi;
  - composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - composer update --no-interaction --no-progress $COMPOSER_FLAGS

before_script:
  - mkdir Snc && ln -s ../ Snc/RedisBundle

script:
  - bin/phpunit
