language: php

services:
  - redis-server

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 7.2
    - php: 7.3
      env: SYMFONY_VERSION="4.3.*""
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"
    - php: nightly
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="4.4.*" SYMFONY_DEPRECATIONS_HELPER="weak" STABILITY="dev"

dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ ${TRAVIS_PHP_VERSION} != hhvm ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - php -i | grep -i --color=never "Redis Version"
  - if [[ ${TRAVIS_PHP_VERSION} != hhvm ]]; then phpenv rehash; fi;
  - composer self-update
  - if ! [ -z "${STABILITY}" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;
  - for PORT in {7000..7008}; do sudo redis-server --port ${PORT} --cluster-enabled yes --cluster-config-file ${PORT}.conf --daemonize yes; echo 127.0.0.1:${PORT}; done
  - echo yes | redis-cli --cluster create $(seq -f 127.0.0.1:%g 7000 7008) --cluster-replicas 2

install:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - composer update --no-interaction --no-progress ${COMPOSER_FLAGS}

script:
  - composer validate --strict --no-check-lock
  - bin/phpunit -v
