language: php

services:
  - redis-server

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION="3.4.*" COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*"
    - php: 7.4
      env: SYMFONY_VERSION="4.4.*"
    - php: 8.0
      env: SYMFONY_VERSION="4.4.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.0.*"
    - php: 8.0
      env: SYMFONY_VERSION="5.0.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.1.*"
    - php: 8.0
      env: SYMFONY_VERSION="5.1.*"
    - php: 7.4
      env: SYMFONY_VERSION="5.2.*" STABILITY="dev"
    - php: 8.0
      env: SYMFONY_VERSION="5.2.*" STABILITY="dev"

  allow_failures:
    - php: 7.4
      env: SYMFONY_VERSION="5.2.*" STABILITY="dev"
    - php: 8.0
      env: SYMFONY_VERSION="5.2.*" STABILITY="dev"

dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [[ ${TRAVIS_PHP_VERSION} != hhvm ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - php -i | grep -i --color=never "Redis Version"
  - if [[ ${TRAVIS_PHP_VERSION} != hhvm ]]; then phpenv rehash; fi;
  - composer self-update
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - if ! [ -z "${STABILITY}" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if [ "${SYMFONY_VERSION}" != "" ]; then composer config extra.symfony.require ${SYMFONY_VERSION}; fi;
  - for PORT in {7000..7008}; do sudo redis-server --port ${PORT} --cluster-enabled yes --cluster-config-file ${PORT}.conf --daemonize yes; echo 127.0.0.1:${PORT}; done
  - echo yes | redis-cli --cluster create $(seq -f 127.0.0.1:%g 7000 7008) --cluster-replicas 2
install:
  - composer update --prefer-dist --no-interaction --no-progress ${COMPOSER_FLAGS}

script:
  - composer validate --strict --no-check-lock
  - bin/phpunit -v
