name: "CI"

on:
  push:
  pull_request:

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-latest"
    env:
      SYMFONY_REQUIRE: "${{matrix.symfony-require}}"
      SYMFONY_DEPRECATIONS_HELPER: "max[self]=0"

    strategy:
      fail-fast: false
      matrix:
        include:
          - dependency-versions: "lowest"
            php-version: "8.2"
            php-extensions: "redis-5.3.2"
          - symfony-require: "6.4.*"
            php-version: "8.3"
            php-extensions: "redis"
          - symfony-require: "7.*"
            php-version: "8.4"
            php-extensions: "redis"
          - symfony-require: "8.*"
            php-version: "8.4"
            php-extensions: "redis"
          - symfony-require: "8.*"
            php-version: "8.5"
            php-extensions: "redis-phpredis/phpredis@develop"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2
      - name: "Install redis server"
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.x"
          auto-start: 'false'
      - name: "Install cli for Procfile"
        run: sudo apt-get update && sudo apt-get install --no-install-recommends ruby-foreman
      - name: "Start background services"
        run: foreman start &
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ matrix.php-extensions }},relay"
          ini-values: "zend.assertions=1, max_execution_time=30"
          tools: "flex"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"

      - name: "Run PHPUnit"
        run: vendor/bin/phpunit
